name: flutter_calendar_carousel
description: Calendar widget for flutter that is swipeable. This widget can help you build customizable calendar with scrollable actions.
version: 1.4.0
author: dooboolab<dooboolab@gmail.com>
homepage: https://github.com/dooboolab/flutter_calendar_carousel

environment:
  sdk: "2.10.5"

dependencies:
  intl: 0.16.1
  flutter:
    sdk: flutter
  date_utils:
  date_util:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
